[33mWARNING [0m root:test_doit5.py:22 i am writing logs now...