{"name": "test_print13", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 15\n  +14\n  -15", "trace": "def test_print13():\n        num = 14\n        logging.info('i am writing logs...')\n        logger.info('i am writing logs 2...')\n        printknow2()\n>       assert num == 15\nE       assert 14 == 15\nE         +14\nE         -15\n\napiauto\\test_doit5.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "b2571825-3308-4522-84e5-0b93797aedd0-attachment.txt", "type": "text/plain"}], "start": 1684305735869, "stop": 1684305735869, "uuid": "c2d3eaba-4179-452a-b511-56ae624328a7", "historyId": "5c84f781d22b7be0851bd3e9e748571e", "testCaseId": "3da96bdadbc715439175681859fa033d", "fullName": "apiauto.test_doit5#test_print13", "labels": [{"name": "parentSuite", "value": "apiauto"}, {"name": "suite", "value": "test_doit5"}, {"name": "host", "value": "DESKTOP-S1E0NQI"}, {"name": "thread", "value": "11072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "apiauto.test_doit5"}]}